### ISSUE TITLE
Troubleshooting installation wiki

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/planning#12]
I want to create a github wiki with information on troubleshooting installation, so when we run across an installation issue, we can more easily document and keep track of how it's solved.  What repo should I put that page in? Here in planning? Should we have a workshop-information repo?

**Comment by karthik** [comment]
I'd vote for another repo.

**Comment by tracykteal** [comment]
workshop-organization? I can see a lot of useful things that could go in there.

**Comment by ethanwhite** [comment]
works for me.

**Comment by fmichonneau** [comment]
+1 for workshop-organization

**Comment by tracykteal** [comment]
done! 
https://github.com/datacarpentry/workshop-organization/
I just set it up to have the gh-pages branch

troubleshooting installation wiki: 
https://github.com/datacarpentry/workshop-organization/wiki/Troubleshooting-installation
