### ISSUE TITLE
How to handle PRs that have new datasets

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/planning#13]
Hopefully this will settle down a bit as we decide on datasets, but since we're not hosting data in the repos, how should we handle PRs that have and need new datasets? Should we have a temporary place for datasets, where we can link to them, and then we can just add the data to FigShare and change the link after a PR has been accepted? Other thoughts or strategies?

**Comment by ethanwhite** [comment]
I think this probably depends a bit on the dataset. If it's available in the form we want to use it in on the web then we should just link to it. If not, then we do need a place to stash it. The question is whether that should be in some sort of official DC location or whether the person developing the lesson should just post it wherever is convenient for them (a public dropbox link, a gist, in the PR but to be cleaned out before the final merge, etc.). My initial reaction would to just let the developer post wherever is easy and convenient for them. We could have language like:

> We don't store data for lessons inside the lesson repositories. For completed lessons the data should be publicly available in a data repository appropriate to the data type. For lesson development the data may be provided in any way that is convenient including posting to a website, a public dropbox link, a GitHub gist, or even included in the PR. Once the PR is ready to merge the data should be placed in the official data repository and all links to the data updated.

My two cents.

**Comment by fmichonneau** [comment]
I agree with @ethanwhite. I'll open a PR against R-ecology with this wording and we can take it from there.

**Comment by hlapp** [comment]
> On Jun 11, 2015, at 7:49 AM, Ethan White notifications@github.com wrote:
> 
> We could have language like:
> 
> We don't store data for lessons inside the lesson repositories. For completed lessons the data should be publicly available in a data repository appropriate to the data type. For lesson development the data may be provided in any way that is convenient including posting to a website, a public dropbox link, a GitHub gist, or even included in the PR. Once the PR is ready to merge the data should be placed in the official data repository and all links to the data updated.

:+1:

**Comment by tracykteal** [comment]
:+1: this seemed to work well for the dplyr PR. Resolve and close?

**Comment by ethanwhite** [comment]
> Resolve and close?

Sounds good to me.

**Comment by karthik** [comment]
👍

**Comment by fmichonneau** [comment]
Thanks, that sounds good.

I'll merge the PR against the R-ecology lesson and will create PRs for the other relevant repositories.
